name: alzcare
description: Compassionate Care for Alzheimer's Patients
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  emoji_picker_flutter: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_local_notifications: ^17.1.2
  video_player: ^2.10.0
  share_plus: 10.0.0
  supabase_flutter: ^2.10.3
  geocoding: ^4.0.0
  supabase: ^2.10.0
  youtube_player_iframe: ^5.0.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  font_awesome_flutter: ^10.6.0
  go_router: ^12.1.3
  http: ^1.1.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.65.0
  url_launcher: ^6.3.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  dio: ^5.7.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.0.17
  google_fonts: ^6.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  loading_animation_widget: ^1.3.0
  flutter_stripe: ^12.0.2
  image_picker: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_phone_direct_caller: ^2.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/png/old-female.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/static/OpenSans-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Open_Sans/static/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Open_Sans/static/OpenSans-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Open_Sans/static/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Open_Sans/static/OpenSans-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Open_Sans/static/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Open_Sans/static/OpenSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Open_Sans/static/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Open_Sans/static/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
